### ISSUE TITLE
Create an email page

### ISSUE THREAD

**Issue by vchelur97** [kshannon-ucsd/cogs9#13]
The email page should contain a certain format and a list of TA/IA/Lecturer emails so that a student can fill it out, and the email will be sent in this specific format to the concerned party.

**Comment by kshannon** [comment]
would be nice to have the following
- subject line is a radio button (required) with pre-canned choices for the subject line, we can make rules for in an email client
- text body (required)
- input for PID, email address, and name (required) which will be put at the top of the email?

**Comment by vchelur97** [comment]
Added in https://github.com/kshannon/ucsd-cogs9/commit/052a312ba3eb35744d7fce468bc973628c85357f
